---
extends: default

rules:
  document-start: disable
  braces:
    max-spaces-inside: 2
    min-spaces-inside: 0
  line-length: disable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0

ignore: |
  pnpm-lock.yaml
